# Generated by Django 4.2.8 on 2023-12-17 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assemblyuser',
            name='phone_number',
            field=models.IntegerField(default=7007975402, max_length=10),
            preserve_default=False,
        ),
    ]
